# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d5875b5e-3e32-4724-ae2e-6522273814cd";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."nixos-crypt".device = "/dev/disk/by-uuid/87f6a43f-6f5d-467e-a5d0-c5264845317f";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d5875b5e-3e32-4724-ae2e-6522273814cd";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/d5875b5e-3e32-4724-ae2e-6522273814cd";
    fsType = "btrfs";
    options = ["subvol=@tmp"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/d5875b5e-3e32-4724-ae2e-6522273814cd";
    fsType = "btrfs";
    options = ["subvol=@var"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EC07-2E9C";
    fsType = "vfat";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
